name: New York Times Best Seller Weekly Updater

on:
  workflow_dispatch:
  schedule:
    - cron: "5 8 * * 0"

env:
  TZ: Asia/Shanghai

jobs:
  NYT-book-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./requirements.txt
      - name: Run Workflow
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "firebaseKey.json"
          encodedString: ${{ secrets.FIREBASE_KEY }}
      - name: Run
        run: python3 ./nyt-fetcher.py ${{ secrets.NEW_YORK_TIMES_API_KEY}}
